### PR TITLE
fix(ui-ux): adjust fees and to receive on UI

### LINKED ISSUE #628: [UI] Changes to Display of Fees
**What?**
When going DFC -> EVM on quantum, the `to receive` field displays the users input amount, but in actuality they will receive a different value (`input value` - `0.3% of input value`)

We need to update the core UI to display the actual amount the user will receive. 

The DSM has been updated with the below changes to reflect this:

- Swapped positions of `to receive` and `fees`
- Added emphasis on the `to receive` value with a slightly larger text. Also this should deduct the fees to better transparency and communication

EVM -> DFC update
image (11)

DFC -> EVM update
image (12)

### PR DESCRIPTION
**Pull request by G9000**
#### What this PR does / why we need it:
As per title

#### Which issue(s) does this PR fixes?:

Fixes #628

#### Developer Checklist:

- [x] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

### CODE REVIEW

File: apps/web/src/components/BridgeForm.tsx [hunk 1]
```diff
@@ -449,6 +437,18 @@ export default function BridgeForm({
           trimTrailingZeros
         />
       </div>
+      <div className="flex flex-row justify-between items-center px-3 lg:px-5 mt-4 lg:mt-[18px]">
+        <span className="text-dark-700 text-xs lg:text-base font-semibold md:font-normal">
+          To receive
+        </span>
+        <NumericFormat
+          className="max-w-[70%] block break-words text-right text-dark-1000 text-sm leading-5 lg:text-lg lg:leading-6 font-bold"
+          value={amount || 0}
```
Comment (lykalabrada) [inline apps/web/src/components/BridgeForm.tsx:446]: Please check **DFC -> EVM update** from the ticket. `To receive` field should show amount with deducted fees

**Review by lykalabrada — CHANGES_REQUESTED** [review]

File: apps/web/src/components/BridgeForm.tsx (hunk 1 above)
Comment (lykalabrada) [reply apps/web/src/components/BridgeForm.tsx:446]: And let's make sure amount with deducted fees will also reflect on the `Review Transaction` modal 🙂 
image

**Review by lykalabrada — APPROVED** [review]
